version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Wr!ghTer555
    expose: 
      - 3306
    deploy:
      replicas: 1
  wordpress:
    depends_on:
       - mysql
    image: wordpress:latest
    restart: always
    ports:
      - 8081:80
    volumes:
      - ./www:/var/www/html
    environment:
      WORDPRESS_DB_PASSWORD: Wr!ghTer555
      WORDPRESS_DB_HOST: mysql
    deploy:
      replicas: 1
  
